server:
  port: 8080

spring:
  application:
    name: vote-hae-duo
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  profiles:
    active: local

kakao:
  api:
    endpoint: "https://kauth.kakao.com"
    client-id: "8a7cea0d9087476d8f483c23b9637587"
    redirect-url: "http://localhost:8080/oauth/redirect"

---
spring:
  config:
    activate:
      on-profile: local
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test;mode=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    generate-ddl: true
    open-in-view: false
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
  sql:
    init:
      data-locations:
        - classpath:/import.sql

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://votehaeduodb.cjopywzdjxoo.ap-northeast-2.rds.amazonaws.com:3306/VoteHaeDuo?useUnicode=true&characterEncoding=utf8
    username: Jun
    password: 99383879
  jpa:
    properties:
      hibernate:
        connection:
          charset: UTF-8
          useUnicode: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  logging:
    level:
      org:
        hibernate:
          SQL: INFO
          type:
  sql:
    init:
      encoding: UTF-8